### ISSUE TITLE
Action Fails To Run on Self-Hosted Runners

### ISSUE THREAD

**Issue by mcaulifn** [reviewdog/action-tflint#36]
Self-hosted runners may not allow `sudo` for the runner user. 

```
Installing /tmp/tflint to /usr/local/bin...
  sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
  sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
  Failed to install tflint
```

Can a test be run for the existence of the binary prior to install? Self-hosted runners would be responsible for installing the tool prior to running the action.

**Comment by Vlaaaaaaad** [comment]
Hey! Sorry about the delay, I took a mental health break!

Right now work is underway to get https://github.com/reviewdog/action-tflint/pull/35 merged. That PR moves to installing all binaries in a temporary directory dedicated to this action. I think that may alleviate this issue.

On the other hand, checking for a pre-existing `tflint` binary makes sense 🤔 I can't think of a reason why this action would require its own `tflint`. What do you think @reviewdog/actions-maintainer?

If the other people from @reviewdog/actions-maintainer agree, we can implement this as a follow-up PR after https://github.com/reviewdog/action-tflint/pull/35/ is merged.

**Comment by haya14busa** [comment]
Are there any reasons why we want to support pre-installed (custom) tflint other than the failure?
It's ok to support it, but note that it may introduce additional maintenance problems. 
For example, if we want to use new features or flags of tflint in this action, it's difficult to use them since users may use older tflint.

I prefer installing tflint in this action if there are no strong reason to support custom tflint.

**Comment by mcaulifn** [comment]
@Vlaaaaaaad I can appreciate the mental health break :)

It looks like #35 resolved this as it is now installing in a tmp directory. Thank you!

```
🐶 Installing reviewdog (v0.11.0) ... https://github.com/reviewdog/reviewdog
  reviewdog/reviewdog info checking GitHub for tag 'v0.11.0'
  reviewdog/reviewdog info found version: 0.11.0 for v0.11.0/Linux/x86_64
  reviewdog/reviewdog info installed /tmp/tmp.qbjymf6R9G/reviewdog/reviewdog
```
