### ISSUE TITLE
GHES Native Support

### ISSUE THREAD

**Issue by mcaulifn** [reviewdog/action-tflint#37]
It looks like part of this action is not properly detecting when the API URL is for GHES. Per the [Environment Variables](https://docs.github.com/en/enterprise-server@3.0/actions/reference/environment-variables#default-environment-variables) doc, `GITHUB_API_URL` is available to use.

```
 Running tflint with reviewdog 🐶 ...
  reviewdog: post failed for tflint: fail to parse diff: GET https://api.github.com/repos/myorg/myrepo/pulls/31: 401 Bad credentials []
Error: Process completed with exit code 1.

**Comment by Vlaaaaaaad** [comment]
Oh, fabulous: GitHub sets the URL in [`GITHUB_API_URL`](https://docs.github.com/en/enterprise-server@3.0/actions/reference/environment-variables#default-environment-variables) and reviewdog expects the URL in  [`GITHUB_API`](https://github.com/reviewdog/reviewdog#reporter-github-pullrequest-review-comment--reportergithub-pr-review) 😆 

@mcaulifn can you try https://github.com/reviewdog/action-tflint/pull/38 and see if it works? I don't have access to a GHES instance.

--- 

Aside: thank you for all the issues with more complex GitHub setups, this is a great help!

**Comment by mcaulifn** [comment]
Happy to help break things 😉

**Comment by shogo82148** [comment]
fixed by https://github.com/reviewdog/action-tflint/pull/40
