### ISSUE TITLE
403 while getting tflint

### ISSUE THREAD

**Issue by dodwmd** [reviewdog/action-tflint#61]
The curl command to download tflint should use the github token to stop 403 errors.

`curl: (22) The requested URL returned error: 403`

By adding  -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" to the request the concurrency bucket is larger.

**Comment by harrywm** [comment]
Bump on this. Just had the same in my action.

```

Preparing
  Detected linux running on amd64, will install tools in /tmp/tmp.WUevwHijof
  Looking up the latest tflint version ...
  curl: (22) The requested URL returned error: 403

```

**Comment by dezren39** [comment]
this is impacting my team too, i look forward to this change.
